local hex = require("c3po.output.hex")
local hex_short = require("c3po.output.hex_short")
local css_rgb = require("c3po.output.css_rgb")
local css_hsl = require("c3po.output.css_hsl")
local css_hwb = require("c3po.output.css_hwb")
local css_lab = require("c3po.output.css_lab")
local css_lch = require("c3po.output.css_lch")
local css_oklab = require("c3po.output.css_oklab")
local css_oklch = require("c3po.output.css_oklch")
local float = require("c3po.output.float")
local latex_rgb = require("c3po.output.latex_rgb")
local latex_rgb_float = require("c3po.output.latex_rgb_float")
local latex_cmyk = require("c3po.output.latex_cmyk")
local latex_html = require("c3po.output.latex_html")
local latex_gray = require("c3po.output.latex_gray")
local latex_gray15 = require("c3po.output.latex_gray15")
local latex_cmy = require("c3po.output.latex_cmy")
local latex_hsb = require("c3po.output.latex_hsb")
local latex_hsb360 = require("c3po.output.latex_hsb360")
local latex_hsb240 = require("c3po.output.latex_hsb240")
local latex_thsb = require("c3po.output.latex_thsb")

---@param colorOutput c3po.ColorOutput
---@param RGB integer[] # range in (0, 255)
---@param A? Alpha
---@param expected string
local function output_test(colorOutput, RGB, A, expected)
  RGB = vim.tbl_map(function(x)
    return x / 255
  end, RGB)
  local actual = colorOutput.str(RGB, A)
  assert.are.equal(expected, actual, ("expected %s, but passed in %s"):format(expected, actual))
end

describe("output", function()
  describe("hex", function()
    it("only RGB", function()
      output_test(hex, { 255, 0, 0 }, nil, "#ff0000")
    end)
    it("with Alpha", function()
      output_test(hex, { 255, 0, 0 }, 1, "#ff0000ff")
    end)
  end)

  describe("hex_short", function()
    it("only RGB", function()
      output_test(hex_short, { 255, 0, 0 }, nil, "#f00")
    end)
    it("with Alpha", function()
      output_test(hex_short, { 255, 0, 0 }, 1, "#f00f")
    end)
  end)

  describe("css_rgb", function()
    it("only RGB", function()
      output_test(css_rgb, { 255, 0, 0 }, nil, "rgb(255 0 0)")
    end)
    it("with Alpha", function()
      output_test(css_rgb, { 255, 0, 0 }, 1, "rgb(255 0 0 / 100%)")
    end)
  end)

  describe("css_hsl", function()
    it("only RGB", function()
      output_test(css_hsl, { 255, 0, 0 }, nil, "hsl(0 100% 50%)")
    end)
    it("with Alpha", function()
      output_test(css_hsl, { 255, 0, 0 }, 1, "hsl(0 100% 50% / 100%)")
    end)
  end)

  describe("css_hwb", function()
    it("only RGB", function()
      output_test(css_hwb, { 0, 0, 255 }, nil, "hwb(240 0% 0%)")
    end)
    it("with Alpha", function()
      output_test(css_hwb, { 0, 0, 255 }, 1, "hwb(240 0% 0% / 100%)")
    end)
  end)

  describe("css_lab", function()
    it("only RGB", function()
      output_test(css_lab, { 128, 128, 128 }, nil, "lab(53.59% 0 0)")
    end)
    it("with Alpha", function()
      output_test(css_lab, { 128, 128, 128 }, 1, "lab(53.59% 0 0 / 100%)")
    end)
  end)

  describe("css_lch", function()
    it("only RGB", function()
      output_test(css_lch, { 255, 0, 0 }, nil, "lch(53.24% 104.54 40)")
    end)
    it("with Alpha", function()
      output_test(css_lch, { 255, 0, 0 }, 1, "lch(53.24% 104.54 40 / 100%)")
    end)
  end)

  describe("css_hsl", function()
    it("only RGB", function()
      output_test(css_hsl, { 255, 0, 0 }, nil, "hsl(0 100% 50%)")
    end)
    it("with Alpha", function()
      output_test(css_hsl, { 255, 0, 0 }, 1, "hsl(0 100% 50% / 100%)")
    end)
  end)

  describe("css_oklab", function()
    it("only RGB", function()
      output_test(css_oklab, { 255, 0, 0 }, nil, "oklab(62.796% 0.22486 0.12585)")
    end)
    it("with Alpha", function()
      output_test(css_oklab, { 255, 0, 0 }, 1, "oklab(62.796% 0.22486 0.12585 / 100%)")
    end)
  end)

  describe("css_oklch", function()
    it("only RGB", function()
      output_test(css_oklch, { 255, 0, 0 }, nil, "oklch(62.796% 0.25768 29.234)")
    end)
    it("with Alpha", function()
      output_test(css_oklch, { 255, 0, 0 }, 1, "oklch(62.796% 0.25768 29.234 / 100%)")
    end)
  end)

  describe("float", function()
    it("only RGB", function()
      output_test(float, { 255, 0, 0 }, nil, "(1.000,0.000,0.000)")
    end)
    it("with Alpha", function()
      output_test(float, { 255, 0, 0 }, 1, "(1.000,0.000,0.000,1.000)")
    end)
  end)
  describe("latex (xcolor)", function()
    it("RGB", function()
      output_test(latex_rgb, { 255, 0, 0 }, nil, "{RGB}{255, 0, 0}")
      output_test(latex_rgb, { 18, 52, 86 }, nil, "{RGB}{18, 52, 86}")
    end)
    it("cmyk", function()
      output_test(latex_cmyk, { 255, 0, 0 }, nil, "{cmyk}{0.000, 1.000, 1.000, 0.000}")
      output_test(latex_cmyk, { 0, 0, 0 }, nil, "{cmyk}{0.000, 0.000, 0.000, 1.000}")
      output_test(latex_cmyk, { 255, 255, 255 }, nil, "{cmyk}{0.000, 0.000, 0.000, 0.000}")
    end)
    it("HTML is uppercase and has no leading #", function()
      output_test(latex_html, { 255, 0, 0 }, nil, "{HTML}{FF0000}")
      output_test(latex_html, { 18, 52, 86 }, nil, "{HTML}{123456}")
    end)
    it("rgb is [0,1] floats", function()
      output_test(latex_rgb_float, { 255, 0, 0 }, nil, "{rgb}{1.000, 0.000, 0.000}")
      output_test(latex_rgb_float, { 18, 52, 86 }, nil, "{rgb}{0.071, 0.204, 0.337}")
    end)
    it("gray uses xcolor's luma weights", function()
      output_test(latex_gray, { 255, 255, 255 }, nil, "{gray}{1.000}")
      output_test(latex_gray, { 0, 0, 0 }, nil, "{gray}{0.000}")
      output_test(latex_gray, { 255, 0, 0 }, nil, "{gray}{0.300}")
    end)
    it("Gray is the same luma on [0, 15] integers", function()
      output_test(latex_gray15, { 255, 255, 255 }, nil, "{Gray}{15}")
      output_test(latex_gray15, { 0, 0, 0 }, nil, "{Gray}{0}")
      output_test(latex_gray15, { 255, 0, 0 }, nil, "{Gray}{5}")
    end)
    it("cmy is the rgb complement", function()
      output_test(latex_cmy, { 255, 0, 0 }, nil, "{cmy}{0.000, 1.000, 1.000}")
      output_test(latex_cmy, { 255, 255, 255 }, nil, "{cmy}{0.000, 0.000, 0.000}")
    end)
    it("hsb scales the hue to [0,1]", function()
      output_test(latex_hsb, { 255, 0, 0 }, nil, "{hsb}{0.000, 1.000, 1.000}")
      output_test(latex_hsb, { 0, 255, 0 }, nil, "{hsb}{0.333, 1.000, 1.000}")
    end)
    it("Hsb keeps the hue in degrees", function()
      output_test(latex_hsb360, { 255, 0, 0 }, nil, "{Hsb}{0.0, 1.000, 1.000}")
      output_test(latex_hsb360, { 0, 255, 0 }, nil, "{Hsb}{120.0, 1.000, 1.000}")
    end)
    it("HSB scales everything to [0, 240]", function()
      output_test(latex_hsb240, { 255, 0, 0 }, nil, "{HSB}{0, 240, 240}")
      output_test(latex_hsb240, { 0, 255, 0 }, nil, "{HSB}{80, 240, 240}")
    end)
    it("tHsb walks the tuning polyline backwards", function()
      output_test(latex_thsb, { 255, 0, 0 }, nil, "{tHsb}{0.0, 1.000, 1.000}")
      -- Hsb hue 120 (green) sits at tuned hue 180 in the default tuning.
      output_test(latex_thsb, { 0, 255, 0 }, nil, "{tHsb}{180.0, 1.000, 1.000}")
      -- Hsb hue 30.1 (orange) crosses into the second segment: tuned hue 60.2.
      output_test(latex_thsb, { 255, 128, 0 }, nil, "{tHsb}{60.2, 1.000, 1.000}")
    end)
  end)

  describe("round trip through the text format", function()
    local utils = require("c3po.utils")
    local pairs_under_test = {
      { css_rgb, require("c3po.picker.css_rgb") },
      { css_hsl, require("c3po.picker.css_hsl") },
      { css_hwb, require("c3po.picker.css_hwb") },
      { css_lab, require("c3po.picker.css_lab") },
      { css_lch, require("c3po.picker.css_lch") },
      { css_oklab, require("c3po.picker.css_oklab") },
      { css_oklch, require("c3po.picker.css_oklch") },
    }

    ---@param output c3po.ColorOutput
    ---@param picker c3po.ColorPicker
    ---@param rgb integer[] # range in (0, 255)
    local function assert_round_trip(output, picker, rgb)
      local RGB = vim.tbl_map(function(x)
        return x / 255
      end, rgb)
      local str = output.str(RGB)
      local _, _, parsed = picker:parse_color(str)
      assert.is_truthy(parsed, ("%s did not parse back"):format(str))
      local back = vim.tbl_map(function(x)
        return utils.round(x * 255)
      end, parsed)
      assert.are.same(rgb, back, ("%s came back as #%02x%02x%02x"):format(str, unpack(back)))
    end

    it("every css output is exact on 8-bit colors", function()
      for _, pair in ipairs(pairs_under_test) do
        for r = 0, 255, 51 do
          for g = 0, 255, 51 do
            for b = 0, 255, 51 do
              assert_round_trip(pair[1], pair[2], { r, g, b })
            end
          end
        end
        -- the color that exposed the integer rounding: #C0BA17 turned into #c0ba16
        assert_round_trip(pair[1], pair[2], { 0xC0, 0xBA, 0x17 })
        assert_round_trip(pair[1], pair[2], { 1, 2, 3 })
        assert_round_trip(pair[1], pair[2], { 254, 253, 252 })
      end
    end)
  end)
end)
